### ISSUE TITLE
Board invisible on old browsers

### ISSUE THREAD

**Issue by AhsanSarwar45** [gtim/svelte-chessground#10]
This has to do with the `aspect-ratio` property in `.cg-wrap`. Even though all new versions of browsers support it, some versions around 2-3 years old don't. As a result, the board is completely invisible on such browsers. The fix is simple though.

```css
.cg-wrap {
    width: 100%;
    aspect-ratio: 1;
}

/* Add fallback for old browsers */
@supports not (aspect-ratio: 1) {
    .cg-wrap {
      padding-top: 100%;
    }
}
```

I can create a PR if you want to support these browsers.
